// User Action Types
export const AddUserToStore = "USER.ADDUSERTOSTORE";

//Product Action Types
export const ADD_PRODUCTS_TOSTORE = "PRODUCT.ADD_PRODUCTS_TOSTORE";
export const FETCH_PRODUCTS_FULFILLED = "PRODUCT.FETCH_PRODUCTS_FULFILLED";
export const FETCH_PRODUCTS_REJECTED = "PRODUCT.FETCH_PRODUCTS_REJECTED";

//For Cart //action types for cart operations
export const ADD_ITEM = "CART.ADD_ITEM";
export const REMOVE_ITEM = "CART.REMOVE_ITEM";
export const UPDATE_ITEM = "CART.UPDATE_ITEM";
export const EMPTY_CART = "CART.EMPTY_CART";

//For coupon
export const ADD_COUPONS = "COUPON.ADD_COUPONS";


// Order Action Types
export const ADD_RECENT_ORDER = 'ORDER.ADD_RECENT_ORDER';
export const FETCH_RECENT_ORDERS_SUCCESS = 'ORDER.FETCH_RECENT_ORDERS_SUCCESS'; 
export const FETCH_ORDERS_FAILURE = 'ORDER.FETCH_ORDERS_FAILURE'; 
export const UPDATE_ORDER = 'ORDER.UPDATE_ORDER'; 
export const UPDATE_ORDER_SUCCESS = 'ORDER.UPDATE_ORDER_SUCCESS'; 
export const UPDATE_ORDER_FAILURE = 'ORDER.UPDATE_ORDER_FAILURE'; 
export const CANCEL_ORDER = 'ORDER.CANCEL_ORDER'; 
export const CANCEL_ORDER_SUCCESS = 'ORDER.CANCEL_ORDER_SUCCESS'; 
export const FETCH_CANCELLED_ORDERS_FAILURE = 'ORDER.FETCH_CANCELLED_ORDERS_FAILURE'; 
export const FETCH_CANCELLED_ORDERS_SUCCESS = 'ORDER.FETCH_CANCELLED_ORDERS_SUCCESS'; 
export const CANCEL_ORDER_FAILURE = 'ORDER.CANCEL_ORDER_FAILURE';
export const MARK_ORDER_AS_DELIVERED = 'ORDER.MARK_ORDER_AS_DELIVERED'; 




